// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLaDX9T9Jb5lPH1P-wFtDkrumWZJQlSDE',
    appId: '1:276027777653:android:c537b06e5cc8d714adce3c',
    messagingSenderId: '276027777653',
    projectId: 'family-budget-app-we105',
    storageBucket: 'family-budget-app-we105.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf4JmQjHs6INBCV3iUGB9_An07DCHx8q8',
    appId: '1:276027777653:ios:1ceeecdd5e393ef6adce3c',
    messagingSenderId: '276027777653',
    projectId: 'family-budget-app-we105',
    storageBucket: 'family-budget-app-we105.firebasestorage.app',
    iosBundleId: 'com.example.familyBudgetApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLaDX9T9Jb5lPH1P-wFtDkrumWZJQlSDE',
    appId: '1:276027777653:web:familybudgetapp',
    messagingSenderId: '276027777653',
    projectId: 'family-budget-app-we105',
    authDomain: 'family-budget-app-we105.firebaseapp.com',
    storageBucket: 'family-budget-app-we105.firebasestorage.app',
  );
}
